AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Catalog for the Data Master Project

Resources:

  StageCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_stage

  BronzeCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_bronze

  SilverCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_silver

  GoldCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_gold

  CostsCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_costs

Outputs:

  StageDatabaseName:
    Description: Glue database for staging layer
    Value: !Ref StageCatalog
    Export:
      Name: dm-stage-db

  BronzeDatabaseName:
    Description: Glue database for bronze layer
    Value: !Ref BronzeCatalog
    Export:
      Name: dm-bronze-db

  SilverDatabaseName:
    Description: Glue database for silver layer
    Value: !Ref SilverCatalog
    Export:
      Name: dm-silver-db

  GoldDatabaseName:
    Description: Glue database for gold layer
    Value: !Ref GoldCatalog
    Export:
      Name: dm-gold-db

  CostsDatabaseName:
    Description: Glue database for costs reports
    Value: !Ref CostsCatalog
    Export:
      Name: dm-costs-db
