AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Catalog for the Data Master Project

Resources:

  StageCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_stage

  BronzeCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_bronze

  SilverCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_silver

  GoldCatalog:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: dm_gold

  FirehoseTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StageCatalog
      TableInput:
        Name: firehose_stream
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          EXTERNAL: "TRUE"
        StorageDescriptor:
          Columns:
            - Name: payload
              Type: string
          Location: !Join ["", ["s3://", !ImportValue dm-stage-bucket, "/streaming/"]]
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Compressed: true
          NumberOfBuckets: -1
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
            Parameters:
              serialization.format: "1"
          StoredAsSubDirectories: false

Outputs:

  StageDatabaseName:
    Description: Glue database for staging layer
    Value: !Ref StageCatalog
    Export:
      Name: dm-stage-db

  BronzeDatabaseName:
    Description: Glue database for bronze layer
    Value: !Ref BronzeCatalog
    Export:
      Name: dm-bronze-db

  SilverDatabaseName:
    Description: Glue database for silver layer
    Value: !Ref SilverCatalog
    Export:
      Name: dm-silver-db

  GoldDatabaseName:
    Description: Glue database for gold layer
    Value: !Ref GoldCatalog
    Export:
      Name: dm-gold-db
