AWSTemplateFormatVersion: '2010-09-09'
Description: Resources used for querying and analyzing data in the Data Master Project

Resources:

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: dm-workgroup
      Description: Athena Workgroup for querying and managing Iceberg tables in the Data Master project
      State: ENABLED
      WorkGroupConfiguration:
        EngineVersion:
          SelectedEngineVersion: "Athena engine version 3"
        ResultConfiguration:
          OutputLocation:
            Fn::Sub:
              - "s3://${Bucket}/athena/"
              - Bucket: !ImportValue dm-observer-bucket
        EnforceWorkGroupConfiguration: true
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Consumption

Outputs:

  AthenaWorkGroupName:
    Description: Athena workgroup name for Iceberg queries
    Value: !Ref AthenaWorkGroup
    Export:
      Name: dm-athena-workgroup-name
