AWSTemplateFormatVersion: "2010-09-09"
Description: IAM user with restricted access to dm_gold (for demonstration purposes)

Resources:

  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub dm-demo-${AWS::AccountId}

  DemoUser:
    Type: AWS::IAM::User
    Properties:
      UserName: dm-demo-user
      LoginProfile:
        Password: DemoUser123!
        PasswordResetRequired: true

  DemoUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: dm-demo-gold-read-access
      Users:
        - !Ref DemoUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AthenaConsoleAccess
            Effect: Allow
            Action:
              - athena:GetWorkGroup
              - athena:ListWorkGroups
              - athena:GetDataCatalog
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:ListEngineVersions
              - athena:ListTagsForResource
            Resource:
              - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary
              - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/dm-athena-workgroup
              - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:datacatalog/AwsDataCatalog
          - Sid: GlueGoldAccess
            Effect: Allow
            Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:GetPartition
              - glue:GetPartitions
            Resource:
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/dm_gold
              - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/dm_gold/*
          - Sid: S3GoldReadAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::dm-datalake
              - arn:aws:s3:::dm-datalake/gold/*
          - Sid: AthenaQueryResults
            Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::dm-demo-${AWS::AccountId}
              - !Sub arn:aws:s3:::dm-demo-${AWS::AccountId}/*
          - Sid: ListBucketsForAthena
            Effect: Allow
            Action:
              - s3:ListAllMyBuckets
            Resource: "*"
          - Sid: LakeFormationDataAccess
            Effect: Allow
            Action:
              - lakeformation:GetDataAccess
            Resource: "*"

  GrantLakeFormationAccess:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !GetAtt DemoUser.Arn
      Permissions:
        - SELECT
      Resource:
        TableResource:
          DatabaseName: dm_gold
          TableWildcard: { }

Outputs:

  DemoBucketName:
    Description: Name of the S3 bucket created for demo results
    Value: !Ref DemoBucket
    Export:
      Name: DemoBucketName

  DemoUserName:
    Description: IAM user name created for the demo
    Value: !Ref DemoUser
    Export:
      Name: DemoUserName
