AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Functions for the Data Master Project

Resources:

  FirehoseRouterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dm-firehose-router
      Description: Used by Firehose to route records into raw S3 prefixes based on table metadata.
      Role: !ImportValue dm-firehose-router-role-arn
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !ImportValue dm-artifacts-bucket
        S3Key: firehose-router.zip
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Functions

  ProcessingControllerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dm-processing-controller
      Description: Responsible for registering incoming raw S3 objects in the processing control table.
      Role: !ImportValue dm-processing-controller-function-role-arn
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !ImportValue dm-artifacts-bucket
        S3Key: processing-controller.zip
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value:
            Functions

  BronzeIngestorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dm-bronze-ingestor-lite
      Description: Responsible for processing raw payloads and converting them to Parquet files in the bronze layer.
      Role: !ImportValue dm-worker-role-arn
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !ImportValue dm-artifacts-bucket
        S3Key: bronze-ingestor-lite.zip
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Functions

  SilverProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dm-silver-processor
      Description: Responsible for processing bronze Parquet files and merging data into Iceberg tables in the silver layer.
      Role: !ImportValue dm-worker-role-arn
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !ImportValue dm-artifacts-bucket
        S3Key: silver-processor.zip
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 900
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Functions

Outputs:

  FirehoseRouterFunctionArn:
    Description: ARN of the Lambda used to set dynamic prefixes in Firehose delivery
    Value: !GetAtt FirehoseRouterFunction.Arn
    Export:
      Name: dm-firehose-router-arn

  ProcessingControllerFunctionArn:
    Description: ARN of the Lambda used to register ingestion processes into the DynamoDB control table
    Value: !GetAtt ProcessingControllerFunction.Arn
    Export:
      Name: dm-processing-controller-arn

  BronzeIngestorFunctionArn:
    Description: ARN of the Lambda used to process raw payloads and convert them to Parquet in the bronze layer
    Value: !GetAtt BronzeIngestorFunction.Arn
    Export:
      Name: dm-bronze-ingestor-function-arn

  SilverProcessorFunctionArn:
    Description: ARN of the Lambda used to process bronze Parquet files and merge into Iceberg tables in the silver layer
    Value: !GetAtt SilverProcessorFunction.Arn
    Export:
      Name: dm-silver-processor-function-arn

