AWSTemplateFormatVersion: '2010-09-09'
Description: Governance Stack for the Data Master Project (Lake Formation)

Resources:

  RegisterLakeLocation:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        Fn::Sub:
          - "arn:aws:s3:::${Bucket}"
          - Bucket: !ImportValue dm-datalake-bucket
      RoleArn: !ImportValue dm-lakeformation-role-arn
      UseServiceLinkedRole: false

  GrantLakeFormationOnStage:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-stage-db
      Permissions:
        - ALL

#  GrantGlueOnStage:
#    Type: AWS::LakeFormation::Permissions
#    Properties:
#      DataLakePrincipal:
#        DataLakePrincipalIdentifier: !ImportValue dm-glue-role-arn
#      Permissions:
#        - SELECT
#        - INSERT
#        - ALTER
#        - DESCRIBE
#      Resource:
#        TableResource:
#          DatabaseName: !ImportValue dm-stage-db
#          TableWildcard: { }

  GrantLakeFormationOnBronze:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-bronze-db
      Permissions:
        - ALL

#  GrantGlueOnBronze:
#    Type: AWS::LakeFormation::Permissions
#    Properties:
#      DataLakePrincipal:
#        DataLakePrincipalIdentifier: !ImportValue dm-glue-role-arn
#      Permissions:
#        - SELECT
#        - INSERT
#        - ALTER
#        - DESCRIBE
#      Resource:
#        TableResource:
#          DatabaseName: !ImportValue dm-bronze-db
#          TableWildcard: { }

  GrantLakeFormationOnSilver:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-silver-db
      Permissions:
        - ALL

#  GrantGlueOnSilver:
#    Type: AWS::LakeFormation::Permissions
#    Properties:
#      DataLakePrincipal:
#        DataLakePrincipalIdentifier: !ImportValue dm-glue-role-arn
#      Permissions:
#        - SELECT
#        - INSERT
#        - ALTER
#        - DESCRIBE
#      Resource:
#        TableResource:
#          DatabaseName: !ImportValue dm-silver-db
#          TableWildcard: { }

  GrantLakeFormationOnGold:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-gold-db
      Permissions:
        - ALL

#  GrantGlueOnGold:
#    Type: AWS::LakeFormation::Permissions
#    Properties:
#      DataLakePrincipal:
#        DataLakePrincipalIdentifier: !ImportValue dm-glue-role-arn
#      Permissions:
#        - SELECT
#        - INSERT
#        - ALTER
#        - DESCRIBE
#      Resource:
#        TableResource:
#          DatabaseName: !ImportValue dm-gold-db
#          TableWildcard: { }
