AWSTemplateFormatVersion: '2010-09-09'
Description: Governance Stack for the Data Master Project (Lake Formation)

Resources:

  RegisterLakeLocation:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        Fn::Sub:
          - "arn:aws:s3:::${Bucket}"
          - Bucket: !ImportValue dm-datalake-bucket
      RoleArn: !ImportValue dm-lakeformation-role-arn
      UseServiceLinkedRole: false

  GrantLakeFormationOnStage:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-stage-db
      Permissions:
        - ALL

  GrantLakeFormationOnBronze:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-bronze-db
      Permissions:
        - ALL

  GrantLakeFormationOnSilver:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-silver-db
      Permissions:
        - ALL

  GrantLakeFormationOnGold:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-gold-db
      Permissions:
        - ALL

  GrantLakeFormationOnCosts:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-costs-db
      Permissions:
        - ALL