AWSTemplateFormatVersion: '2010-09-09'
Description: Network Stack for the Data Master Project

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: dm-vpc
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: dm-igw
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dm-public-subnet-az1
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dm-public-subnet-az2
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: dm-public-rt
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociationAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociationAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref RouteTable

  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dm-private-subnet-az1
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: dm-private-subnet-az2
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

Outputs:

  VpcId:
    Description: ID of the created VPC
    Value: !Ref VPC
    Export:
      Name: dm-vpc-id

  SubnetIds:
    Description: List of public subnet IDs across two Availability Zones
    Value: !Join [",", [!Ref PublicSubnetAZ1, !Ref PublicSubnetAZ2]]
    Export:
      Name: dm-subnet-ids

  PublicSubnetAZ1Id:
    Description: ID of public subnet in AZ1
    Value: !Ref PublicSubnetAZ1
    Export:
      Name: dm-public-subnet-az1-id

  PublicSubnetAZ2Id:
    Description: ID of public subnet in AZ2
    Value: !Ref PublicSubnetAZ2
    Export:
      Name: dm-public-subnet-az2-id

  PrivateSubnetAZ1Id:
    Description: First private subnet
    Value: !Ref PrivateSubnetAZ1
    Export:
      Name: dm-private-subnet-az1

  PrivateSubnetAZ2Id:
    Description: Second private subnet
    Value: !Ref PrivateSubnetAZ2
    Export:
      Name: dm-private-subnet-az2

  RouteTableId:
    Description: Public Route Table ID for S3 VPCEndpoint
    Value: !Ref RouteTable
    Export:
      Name: dm-public-rt-id
