AWSTemplateFormatVersion: '2010-09-09'
Description: Observability stack with AWS Managed Grafana for Data Master

Resources:

  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      Description: Grafana workspace for Data Master observability
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - SAML
      PermissionType: SERVICE_MANAGED
      PluginAdminEnabled: true
      RoleArn: !ImportValue dm-grafana-access-role-arn
      Name: dm-grafana-workspace
      DataSources:
        - ATHENA
        - CLOUDWATCH

Outputs:

  GrafanaWorkspaceId:
    Description: Workspace ID
    Value: !Ref GrafanaWorkspace
    Export:
      Name: dm-grafana-workspace-id

  GrafanaWorkspaceEndpoint:
    Description: URL to access the Grafana Workspace
    Value: !GetAtt GrafanaWorkspace.Endpoint
    Export:
      Name: dm-grafana-workspace-endpoint
