AWSTemplateFormatVersion: '2010-09-09'
Description: Observability stack with AWS Managed Grafana for Data Master

Resources:

  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: SERVICE_MANAGED
      RoleArn: !ImportValue dm-grafana-role-arn
      Name: dm-grafana
      DataSources:
        - ATHENA
        - CLOUDWATCH
      WorkspaceDataSources:
        - ATHENA
        - CLOUDWATCH
      WorkspaceDescription: Grafana workspace for Data Master observability
      WorkspaceOrganizationalUnits: []
      WorkspaceRoleArn: !ImportValue dm-grafana-role-arn
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Observability

Outputs:

  GrafanaWorkspaceURL:
    Description: URL to access the Grafana Workspace
    Value: !GetAtt GrafanaWorkspace.Endpoint
    Export:
      Name: dm-grafana-endpoint

  GrafanaWorkspaceId:
    Description: Workspace ID
    Value: !Ref GrafanaWorkspace
    Export:
      Name: dm-grafana-workspace-id
