AWSTemplateFormatVersion: '2010-09-09'
Description: Orchestrates the data pipeline process for the Data Master Project

Resources:

  ProcessingControlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "dm-processing-control"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: object_key
          AttributeType: S
      KeySchema:
        - AttributeName: object_key
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Processing

#  ProcessPipelineRule:
#    Type: AWS::Events::Rule
#    Properties:
#      Name: dm-process-pipeline-rule
#      EventPattern:
#        source:
#          - "dm.pipeline"
#        detail-type:
#          - "ProcessObject"
#      Targets:
#        - Arn: !GetAtt ProcessPipelineFunction.Arn
#          Id: ProcessPipelineFunctionTarget
#          InputPath: "$.detail"
#
#  ProcessPipelinePermission:
#    Type: AWS::Lambda::Permission
#    Properties:
#      FunctionName: !Ref BronzeProcessorFunction
#      Action: lambda:InvokeFunction
#      Principal: events.amazonaws.com
#      SourceArn: !GetAtt ProcessPipelineRule.Arn

Outputs:

  ProcessingControlTableName:
    Description: Name of the DynamoDB table used for tracking processed S3 objects
    Value: !Ref ProcessingControlTable
    Export:
      Name: dm-processing-control-table-name

  ProcessingControlStreamArn:
    Description: ARN of the DynamoDB stream for processing control table
    Value: !GetAtt ProcessingControlTable.StreamArn
    Export:
      Name: dm-processing-control-stream-arn
