AWSTemplateFormatVersion: "2010-09-09"
Description: Base repositories for container workloads in the Data Master Project

Parameters:

  DeployerArn:
    Type: String
    Description: ARN of the principal allowed to push images to ECR

Resources:

#  BronzeRepositoryPolicy:
#    Type: AWS::ECR::Repository
#    Properties:
#      RepositoryName: dm-bronze-ingestor-mass
#      RepositoryPolicyText:
#        !Sub
#        - |
#          {
#            "Version": "2012-10-17",
#            "Statement": [
#              {
#                "Sid": "AllowPull",
#                "Effect": "Allow",
#                "Principal": {
#                  "AWS": "${DeployerArn}"
#                },
#                "Action": [
#                  "ecr:BatchCheckLayerAvailability",
#                  "ecr:CompleteLayerUpload",
#                  "ecr:InitiateLayerUpload",
#                  "ecr:PutImage",
#                  "ecr:UploadLayerPart"
#                ]
#              }
#            ]
#          }
#        - DeployerArn: !Ref DeployerArn
#
#  SilverRepositoryPolicy:
#    Type: AWS::ECR::Repository
#    Properties:
#      RepositoryName: dm-silver-processor-mass
#      RepositoryPolicyText:
#        !Sub
#        - |
#          {
#            "Version": "2012-10-17",
#            "Statement": [
#              {
#                "Sid": "AllowPull",
#                "Effect": "Allow",
#                "Principal": {
#                  "AWS": "${DeployerArn}"
#                },
#                "Action": [
#                  "ecr:BatchCheckLayerAvailability",
#                  "ecr:CompleteLayerUpload",
#                  "ecr:InitiateLayerUpload",
#                  "ecr:PutImage",
#                  "ecr:UploadLayerPart"
#                ]
#              }
#            ]
#          }
#        - DeployerArn: !Ref DeployerArn
#
#  GoldRepositoryPolicy:
#    Type: AWS::ECR::Repository
#    Properties:
#      RepositoryName: dm-gold-analytics-mass
#      RepositoryPolicyText:
#        !Sub
#        - |
#          {
#            "Version": "2012-10-17",
#            "Statement": [
#              {
#                "Sid": "AllowPull",
#                "Effect": "Allow",
#                "Principal": {
#                  "AWS": "${DeployerArn}"
#                },
#                "Action": [
#                  "ecr:BatchCheckLayerAvailability",
#                  "ecr:CompleteLayerUpload",
#                  "ecr:InitiateLayerUpload",
#                  "ecr:PutImage",
#                  "ecr:UploadLayerPart"
#                ]
#              }
#            ]
#          }
#        - DeployerArn: !Ref DeployerArn

  BenchmarkRepositoryPolicy:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: dm-benchmark-go
      RepositoryPolicyText:
        !Sub
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AllowPull",
                "Effect": "Allow",
                "Principal": {
                  "AWS": "${DeployerArn}"
                },
                "Action": [
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:CompleteLayerUpload",
                  "ecr:InitiateLayerUpload",
                  "ecr:PutImage",
                  "ecr:UploadLayerPart"
                ]
              }
            ]
          }
        - DeployerArn: !Ref DeployerArn