AWSTemplateFormatVersion: '2010-09-09'
Description: Security Stack for the Data Master Project

Parameters:

  SecretName:
    Type: String
    Default: dm-db-credentials
    Description: Name for the Secrets Manager secret

  DeployerArn:
    Type: String
    Description: ARN of the principal allowed to retrieve the secret

Resources:

  DBAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow database access
      VpcId: !ImportValue dm-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Security

  GlueSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internal Glue access (Spark jobs)
      VpcId: !ImportValue dm-vpc-id
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Security

  GlueSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref GlueSecurityGroup
      IpProtocol: -1
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref GlueSecurityGroup

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: Credentials for the Aurora PostgreSQL Cluster
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dmadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: ";+%@\"'/\\`"
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Security

  DBSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref DBSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAccessToDeployer
            Effect: Allow
            Principal:
              AWS: !Ref DeployerArn
            Action: secretsmanager:GetSecretValue
            Resource: "*"

  DMSVpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for DMS Replication Instance
      VpcId: !ImportValue dm-vpc-id
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Security

  DMSIngressToAurora:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBAccessSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref DMSVpcSecurityGroup

Outputs:

  SecurityGroupId:
    Description: Security Group ID for Aurora
    Value: !Ref DBAccessSecurityGroup
    Export:
      Name: dm-db-sg-id

  GlueSecurityGroupId:
    Description: Security Group ID for Glue Connections
    Value: !Ref GlueSecurityGroup
    Export:
      Name: dm-glue-sg-id

  SecretArn:
    Description: Secret ARN
    Value: !Ref DBSecret
    Export:
      Name: dm-db-secret-arn

  DMSVpcSecurityGroup:
    Description: Security Group ID for DMS Replication Instance
    Value: !Ref DMSVpcSecurityGroup
    Export:
      Name: dm-dms-vpc-sg-id
