AWSTemplateFormatVersion: '2010-09-09'
Description: Storage Buckets for the Data Master Project

Resources:

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dm-source-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Storage

  StageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dm-stage-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Storage

  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dm-datalake-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Storage

  ObserverBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dm-observer-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Storage

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub dm-artifacts-${AWS::AccountId}
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Storage

  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !ImportValue dm-vpc-id
      RouteTableIds:
        - !ImportValue dm-public-rt-id
      VpcEndpointType: Gateway
      Tags:
        - Key: Name
          Value: dm-s3-endpoint
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Network

Outputs:

  SourceBucketName:
    Description: Name of the Source (Batch Ingest) bucket
    Value: !Ref SourceBucket
    Export:
      Name: dm-source-bucket

  StageBucketName:
    Description: Name of the Stage (Parquet Landing) bucket
    Value: !Ref StageBucket
    Export:
      Name: dm-stage-bucket

  DataLakeBucketName:
    Description: Name of the Data Lake bucket
    Value: !Ref DataLakeBucket
    Export:
      Name: dm-datalake-bucket

  ObserverBucketName:
    Description: Name of the Observer bucket
    Value: !Ref ObserverBucket
    Export:
      Name: dm-observer-bucket

  ArtifactsBucketName:
    Description: Name of the Artifacts bucket
    Value: !Ref ArtifactsBucket
    Export:
      Name: dm-artifacts-bucket

  S3VPCEndpointId:
    Description: ID of the S3 VPC Endpoint
    Value: !Ref S3VPCEndpoint
    Export:
      Name: dm-s3-vpc-endpoint-id
