AWSTemplateFormatVersion: '2010-09-09'
Description: Athena workgroup configuration for the Data Master consumption layer

Resources:

  AthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: dm-workgroup
      State: ENABLED
      Description: Workgroup for Data Master Athena queries
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 1000000000  # 1GB
        ResultConfiguration:
          OutputLocation:
            Fn::Sub:
              - "s3://${Bucket}/athena/"
              - Bucket: !ImportValue dm-observer-bucket
        EnforceWorkGroupConfiguration: true
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Consumption

Outputs:

  AthenaWorkgroup:
    Description: Workgroup used for Athena queries
    Value: !Ref AthenaWorkgroup
    Export:
      Name: dm-athena-workgroup
