AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora PostgreSQL Serverless v2 for the Data Master Project

Parameters:

  DatabaseName:
    Type: String
    Default: datamasterdb
    Description: Initial database name

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL
      SubnetIds:
        - !ImportValue dm-public-subnet-az1-id
        - !ImportValue dm-public-subnet-az2-id
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Database

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Cluster parameter group with CDC enabled
      Family: aurora-postgresql16
      Parameters:
        rds.logical_replication: 1
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Database

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: dm-database-cluster
      Engine: aurora-postgresql
      EngineMode: provisioned
      EngineVersion: 16.6
      Port: 5432
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Join [ "", [ "{{resolve:secretsmanager:", !ImportValue dm-db-secret-arn, ":SecretString:username}}" ] ]
      MasterUserPassword: !Join [ "", [ "{{resolve:secretsmanager:", !ImportValue dm-db-secret-arn, ":SecretString:password}}" ] ]
      VpcSecurityGroupIds:
        - !ImportValue dm-db-sg-id
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 1
      EnableCloudwatchLogsExports:
        - postgresql
      EnableHttpEndpoint: true # RDS Data API
      PerformanceInsightsEnabled: true
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Database

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: dm-database-instance-writer
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      PubliclyAccessible: true # WARNING: Only for development!
      Tags:
        - Key: Project
          Value: DataMaster
        - Key: Component
          Value: Database

Outputs:

  ClusterIdentifier:
    Description: DB Cluster Identifier
    Value: dm-database-cluster
    Export:
      Name: dm-db-cluster-identifier

  WriterEndpoint:
    Description: Writer Endpoint of the DB Cluster
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: dm-db-writer-endpoint

  ReaderEndpoint:
    Description: Reader Endpoint of the DB Cluster
    Value: !GetAtt DBCluster.ReadEndpoint.Address
    Export:
      Name: dm-db-reader-endpoint

  DatabasePort:
    Description: Database Port
    Value: 5432
    Export:
      Name: dm-db-port

  DatabaseName:
    Description: Database Name
    Value: !Ref DatabaseName
    Export:
      Name: dm-db-name
