AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora PostgreSQL Serverless v2 Stack for Data Master Case

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs in different AZs
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID
  SecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret
  DatabaseName:
    Type: String
    Default: datamasterdb
    Description: Initial database name

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora PostgreSQL
      SubnetIds: !Ref SubnetIds

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Cluster parameter group with CDC enabled
      Family: aurora-postgresql16
      Parameters:
        rds.logical_replication: 1

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineMode: provisioned
      EngineVersion: 16.6
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref SecretArn
          - ":SecretString:username}}"
      MasterUserPassword: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref SecretArn
          - ":SecretString:password}}"
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 1
      PreferredBackupWindow: 03:00-04:00
      DeletionProtection: false
      EnableCloudwatchLogsExports:
        - postgresql
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup

Outputs:
  ClusterEndpoint:
    Description: Writer Endpoint of the DB Cluster
    Value: !GetAtt DBCluster.Endpoint.Address
  ReaderEndpoint:
    Description: Reader Endpoint of the DB Cluster
    Value: !GetAtt DBCluster.ReadEndpoint.Address
