AWSTemplateFormatVersion: '2010-09-09'
Description: Governance Stack for the Data Master Project (Lake Formation)

Resources:

  RegisterLakeLocation:
    Type: AWS::LakeFormation::Resource
    Properties:
      ResourceArn:
        Fn::Sub:
          - "arn:aws:s3:::${Bucket}"
          - Bucket: !ImportValue dm-datalake-bucket
      RoleArn: !ImportValue dm-lakeformation-role-arn
      UseServiceLinkedRole: false

  GrantLakeFormationDatabasePermission:
    Type: AWS::LakeFormation::Permissions
    Properties:
      DataLakePrincipal:
        DataLakePrincipalIdentifier: !ImportValue dm-lakeformation-role-arn
      Resource:
        DatabaseResource:
          Name: !ImportValue dm-glue-database-name
      Permissions:
        - ALL

Outputs:

  LakeResourceArn:
    Description: Registered S3 location in Lake Formation
    Value:
      Fn::Sub:
        - "arn:aws:s3:::${Bucket}"
        - Bucket: !ImportValue dm-datalake-bucket
    Export:
      Name: dm-lakeformation-s3-arn
